local h = {}

h.PROXY_LOADED = hash("proxy_loaded")
h.LOAD = hash("load")
h.UNLOAD = hash("unload")
h.GAME = hash("game")
h.GAMEOVER = hash("gameover")
h.GAMEOVER_BUTTON = hash("gameover_button")
h.RESTART = hash("restart")
h.START = hash("start")
h.START_BUTTON = hash("start_button")

h.IDLE = hash("idle")
h.WALK = hash("walk")
h.DANCE = hash("dance")
h.DRINK = hash("drink")

h.GO_TO = hash("go_to")
h.QUEUED_ACTION = hash("queued_action")
h.ACTION = hash("action")
h.ACTION_COMPLETE = hash("action_complete")
h.GUEST_TARGET = hash("guest_target")
h.RELEASE_TARGET = hash("release_target")
h.GUEST_COMPLETE =hash("guest_complete")
h.TRIGGER_TALK = hash("trigger_talk")

h.COCKTAIL = hash("cocktail")
h.BOTTLE = hash("bottle")
h.POWDER = hash("powder")
h.MUSIC = hash("music")
h.PHONE = hash("phone")
h.TALK = hash("talk")
h.CHARACTER_COCKTAIL = hash("character_cocktail")
h.CHARACTER_MUSIC = hash("character_music")
h.CHARACTER_TALK = hash("character_talk")
h.CHARACTER_POWDER = hash("character_powder")
h.CHARACTER_CLOSE = hash("character_close")

h.DOWNSTAIRS = hash("downstairs")
h.UPSTAIRS = hash("upstairs")
h.STAIRS = hash("stairs")
h.OUTSIDE = hash("outside")

h.DEFAULT = hash("default")
h.OVER = hash("over")
h.DOWN = hash("down")
h.RELEASED = hash("released")
h.WOBBLE_NODE = hash("wobble_node")
h.HIGHLIGHT_NODE = hash("highlight_node")
h.HIDE_BUTTON = hash("hide_button")
h.SHOW_BUTTON = hash("show_button")
h.LOAD_CHARACTER = hash("load_character")
h.CLOSE = hash("close")

h.TOUCH = hash("touch")
h.MOUSE_BUTTON_RIGHT = hash("mouse_button_right")

h.CLICK = hash("click")

return h